apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
      - achillespanagiotou.com
      - www.achillespanagiotou.com
      - test.organicway.gr
      - test1.achillespanagiotou.com
      - test2.achillespanagiotou.com
      - test3.achillespanagiotou.com
      - test4.achillespanagiotou.com
      - test5.achillespanagiotou.com
      - test6.achillespanagiotou.com
      - test7.achillespanagiotou.com
      - test8.achillespanagiotou.com
      - test9.achillespanagiotou.com
      - test10.achillespanagiotou.com
      - test11.achillespanagiotou.com
      - test12.achillespanagiotou.com
      - test13.achillespanagiotou.com
      - test14.achillespanagiotou.com
      - test15.achillespanagiotou.com
      - test16.achillespanagiotou.com
      - test17.achillespanagiotou.com
      - test18.achillespanagiotou.com
      secretName: ingress-service-cert
  rules:
    - host: achillespanagiotou.com
      http: &paths
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
    - host: www.achillespanagiotou.com
      http: *paths
    - host: test.organicway.gr
      http: *paths
    - host: test1.achillespanagiotou.com
      http: *paths
    - host: test2.achillespanagiotou.com
      http: *paths
    - host: test3.achillespanagiotou.com
      http: *paths
    - host: test4.achillespanagiotou.com
      http: *paths
    - host: test5.achillespanagiotou.com
      http: *paths
    - host: test6.achillespanagiotou.com
      http: *paths
    - host: test7.achillespanagiotou.com
      http: *paths
    - host: test8.achillespanagiotou.com
      http: *paths
    - host: test9.achillespanagiotou.com
      http: *paths
    - host: test10.achillespanagiotou.com
      http: *paths
    - host: test11.achillespanagiotou.com
      http: *paths
    - host: test12.achillespanagiotou.com
      http: *paths
    - host: test13.achillespanagiotou.com
      http: *paths
    - host: test14.achillespanagiotou.com
      http: *paths
    - host: test15.achillespanagiotou.com
      http: *paths
    - host: test16.achillespanagiotou.com
      http: *paths
    - host: test17.achillespanagiotou.com
      http: *paths
    - host: test18.achillespanagiotou.com
      http: *paths
